after-login-command = []

after-startup-command = [
  'exec-and-forget borders active_color=0xff6a6a69 inactive_color=0xff2b2928 width=5.0 blacklist="Substage,iPhone Mirroring,CleanMyMac,Steam,Stickies"'
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 16
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

automatically-unhide-macos-hidden-apps = false

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = [{ monitor.main = 200 }, { monitor.secondary = 255 }, 8]
outer.bottom = [{ monitor.main = 135 }, { monitor.secondary = 135 }, 8]
outer.top = [{ monitor.main = 135 }, { monitor.secondary = 135 }, 8]
outer.right = [{ monitor.main = 200 }, { monitor.secondary = 255 }, 8]

[workspace-to-monitor-force-assignment]
5 = 'main'
6 = 'main'
7 = 'main'
8 = 'main'

[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'

alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-q = 'workspace 5'
alt-w = 'workspace 6'
alt-e = 'workspace 7'
alt-r = 'workspace 8'

alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'

alt-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
alt-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
alt-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
alt-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
alt-shift-q = 'move-node-to-workspace 5 --focus-follows-window'
alt-shift-w = 'move-node-to-workspace 6 --focus-follows-window'
alt-shift-e = 'move-node-to-workspace 7 --focus-follows-window'
alt-shift-r = 'move-node-to-workspace 8 --focus-follows-window'

alt-ctrl-1 = 'move-node-to-monitor 1 --focus-follows-window'
alt-ctrl-2 = 'move-node-to-monitor 2 --focus-follows-window'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-f = 'fullscreen'

alt-shift-semicolon = 'mode service'

alt-shift-enter = 'mode apps'

[mode.apps.binding]
esc = ['mode main']
alt-b = 'exec-and-forget open -a /Applications/Google Chrome.app'
alt-o = 'exec-and-forget open -a /Applications/Obsidian.app'
alt-t = 'exec-and-forget open -a /Applications/Termius.app'
alt-m = 'exec-and-forget open -a /Applications/Texts.app'
alt-e = 'exec-and-forget open -a /Applications/Mail.app'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

# floating windows

[[on-window-detected]]
if.app-name-regex-substring = 'chatgpt'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'perplexity'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'simulator'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'texts'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'telegram'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'whatsapp'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'discord'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'music'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'cleanmymac'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'game'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'iterm'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'ghostty'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'maps'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'fantastical'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'calendar'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'reminders'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'mail'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'obsidian'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'keka'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'permute'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'downie'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'timing'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'linear'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'passwords'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'MGCB Editor'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'Amie'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'Legcord'
run= "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'Beeper'
run= "layout floating"
